# Generated by Django 5.2.4 on 2025-07-21 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('cost_formula', models.TextField()),
                ('time_formula', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=100)),
                ('order_name', models.CharField(max_length=255)),
                ('is_template', models.BooleanField(default=False)),
                ('is_finalized', models.BooleanField(default=False)),
                ('version', models.CharField(default='v01', max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('variant_quantities', models.CharField(blank=True, max_length=100)),
                ('paper_type', models.CharField(max_length=100)),
                ('paper_weight', models.PositiveIntegerField(help_text='g/m²')),
                ('end_size', models.CharField(max_length=50)),
                ('printing_size', models.CharField(max_length=50)),
                ('selling_size', models.CharField(max_length=50)),
                ('parts_of_selling_size', models.PositiveIntegerField()),
                ('n_up', models.PositiveIntegerField()),
                ('colors_front', models.PositiveIntegerField()),
                ('colors_back', models.PositiveIntegerField()),
                ('special_colors', models.PositiveIntegerField()),
                ('num_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('n_up_signatures', models.PositiveIntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.client')),
            ],
        ),
        migrations.CreateModel(
            name='JobOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='jobs.job')),
                ('master_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.masteroperation')),
            ],
        ),
    ]
